# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K-eRwPNP4IiznTsAE9pBpME1iu8uCEXJ
"""

nota1 = 7.5
nota2 = 4.8

def verificar_aprovação():
    media = calcular_media([nota1, nota2])

    if media >= 6:
      print("O aluno foi APROVADO!")
    else:
      print("O aluno foi REPROVADO!")

def calcular_media(notas):
  quantidade = len(notas)

  soma = 0
  for nota in notas:
    soma = soma + nota
  
  media = soma / quantidade

  return media

verificar_aprovação()

frutas = ['Maça', 'Banana', 'Pera', 'Uva']
guloseimas = ['Bolacha', 'Batata', 'Fini', 'Chocolate']
comidas = ['Arroz', 'Feijão', 'Carne']
bebidas = ['Refrigerante', 'Suco de laranja', 'Água']

categorias = ['Frutas', 'Guloseimas', 'Comida', 'Bebidas']
compras = [frutas, guloseimas, comidas, bebidas]

for indice, categoria in enumerate(categorias):
  print('Você precisa comprar', len(compras[indice]), categoria+':')
  for compra in compras[indice]:
    print('-', compra)

